language: python

python:
  - 3.6
  - 3.8
  - nightly
  - pypy3
install:
  - pip install pytest coverage coveralls

# # command to run tests, e.g. python setup.py test
script:
  - coverage run --source=astar -m pytest

after_sucess:
  coveralls
